In [0]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import collections as collect
import time
from sklearn import preprocessing
from sklearn.utils import shuffle
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import Perceptron
from sklearn.neural_network import MLPClassifier
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix 
from sklearn.model_selection import cross_val_score
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

In [0]:
#import and clean dataset
df=pd.read_csv('data.csv')

In [0]:
positive = 'pos'
df[list(df)[0]]=[1 if element==positive else 0 for element in df[list(df)[0]]]
print("# of ones:",np.count_nonzero(df.values[:,0]==1)) 

# of ones: 300


In [0]:
y_ind=0
np.random.shuffle(df.values)
X=df.values[:,y_ind:]
Y=df.values[:,y_ind]
print(X.shape,Y.shape)

(600, 501) (600,)


In [0]:
#Initialize the PCA model, here specifying 300 component
pca = PCA(n_components=300, whiten=True)
# Fit the PCA model, and apply it to transform the data
output = pca.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(output, Y, test_size = 0.20)
#y_test=np.reshape(y_test,(-1,1))
#y_train=np.reshape(y_train,(-1,1))
print(X_train.shape,y_train.shape)
print(X_test.shape,y_test.shape)

(480, 300) (480,)
(120, 300) (120,)


In [0]:
svclassifier = SVC(kernel='linear')  
svclassifier.fit(X_train, y_train) 
scores = cross_val_score(svclassifier, X_train, y_train, cv=5)
print(scores)

[0.73195876 0.72916667 0.72916667 0.6875     0.69473684]


In [0]:
y_pred = svclassifier.predict(X_test)  


In [0]:
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred)) 

[[38 23]
 [13 46]]
              precision    recall  f1-score   support

           0       0.75      0.62      0.68        61
           1       0.67      0.78      0.72        59

   micro avg       0.70      0.70      0.70       120
   macro avg       0.71      0.70      0.70       120
weighted avg       0.71      0.70      0.70       120



In [0]:
svclassifier = SVC(kernel='rbf')  
svclassifier.fit(X_train, y_train) 
scores = cross_val_score(svclassifier, X_train, y_train, cv=5)
print(scores)

/Users/JP/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/Users/JP/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/Users/JP/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


[0.75257732 0.72916667 0.73958333 0.72916667 0.76842105]


/Users/JP/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/Users/JP/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/Users/JP/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [0]:
y_pred = svclassifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred)) 

[[37 24]
 [10 49]]
              precision    recall  f1-score   support

           0       0.79      0.61      0.69        61
           1       0.67      0.83      0.74        59

   micro avg       0.72      0.72      0.72       120
   macro avg       0.73      0.72      0.71       120
weighted avg       0.73      0.72      0.71       120



In [0]:
lda = LDA(n_components=300)  
X_trainLDA = lda.fit_transform(X_train, y_train)  
X_testLDA = lda.transform(X_test)  
scores = cross_val_score(lda, X_trainLDA, y_train, cv=5)
print(scores)

[0.98969072 0.96875    0.95833333 0.97916667 0.98947368]


In [0]:
classifier = RandomForestClassifier(max_depth=2, random_state=0)

classifier.fit(X_trainLDA, y_train)  
y_pred_lda = classifier.predict(X_testLDA) 

/Users/JP/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [0]:
print('                   Random Forest Classifier')
print(confusion_matrix(y_test,y_pred_lda))  
print(classification_report(y_test,y_pred_lda)) 

                   Random Forest Classifier
[[46 15]
 [ 8 51]]
              precision    recall  f1-score   support

           0       0.85      0.75      0.80        61
           1       0.77      0.86      0.82        59

   micro avg       0.81      0.81      0.81       120
   macro avg       0.81      0.81      0.81       120
weighted avg       0.81      0.81      0.81       120



In [0]:
# Train the scaler, which standarizes all the features to have mean=0 and unit variance
sc = StandardScaler()
sc.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [0]:
# Apply the scaler to the X training data
X_train_per = sc.transform(X_train)

# Apply the SAME scaler to the X test data
X_test_per = sc.transform(X_test)

In [0]:
# Create a perceptron object with the parameters: 40 iterations (epochs) over the data, and a learning rate of 0.1
ppn = Perceptron(n_iter=40, eta0=0.1, random_state=0)

# Train the perceptron
ppn.fit(X_train_per, y_train)

/Users/JP/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/stochastic_gradient.py:152: DeprecationWarning: n_iter parameter is deprecated in 0.19 and will be removed in 0.21. Use max_iter and tol instead.
  DeprecationWarning)


Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=0.1,
      fit_intercept=True, max_iter=None, n_iter=40, n_iter_no_change=5,
      n_jobs=None, penalty=None, random_state=0, shuffle=True, tol=None,
      validation_fraction=0.1, verbose=0, warm_start=False)

In [0]:
# Apply the trained perceptron on the X data to make predicts for the y test data
y_pred_per = ppn.predict(X_test_per)
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

Accuracy: 0.72
